common: &default_settings
  adapter: postgresql
  encoding: utf8
  reconnect: false
  pool: 100
  username: postgres_default_user
  password: secret
  host: localhost
  timeout: 5000

development:
  <<: *default_settings
  database: todo_api_sample_development

test:
  <<: *default_settings
  database: todo_api_sample_test

production:
  <<: *default_settings
  database: todo_api_sample_development

# # Add User
# createuser -D -A -P postgres_default_user
# # Remove
# dropdb -e todo_api_sample_development
# # Add Database
# createdb -O postgres_default_user -E UTF8 todo_api_sample_development
# # Verification
# psql -U postgres_default_user -d todo_api_sample_development
# Grant user, connect to PGSL with root or granted user
# psql todo_api_sample_development
# ALTER USER postgres_default_user CREATEDB;

# psql template1
# alter role postgres_default_user with superuser;
